export const applications = [
    { appName: "Sheets", icon: "/appIcons/googleSheet.png" },
    { appName: "Slides", icon: "/appIcons/googleSlides.png" },
    { appName: "Calender", icon: "/appIcons/Calender.png" },
    { appName: "Chrome", icon: "/appIcons/chrome.png" },
    { appName: "Drive", icon: "/appIcons/drive.png" },
    { appName: "Gmail", icon: "/appIcons/gmail.png" },
    { appName: "Google", icon: "/appIcons/google.png" },
    { appName: "GPay", icon: "/appIcons/gpay.png" },
    { appName: "Maps", icon: "/appIcons/map.png" },
    { appName: "Meet", icon: "/appIcons/meet.png" },
    { appName: "Amazon", icon: "/appIcons/amazon.png" },
    { appName: "Calculator", icon: "/appIcons/calculator.png" },
    { appName: "Camera", icon: "/appIcons/camera.png" },
    { appName: "Clock", icon: "/appIcons/clock.png" },
    { appName: "Contacts", icon: "/appIcons/contacts.png" },
    { appName: "Facebook", icon: "/appIcons/facebook.png" },
    { appName: "Files", icon: "/appIcons/fileManager.png" },
    { appName: "Flipkart", icon: "/appIcons/flipkart.png" },
    { appName: "Games", icon: "/appIcons/Games.png" },
    { appName: "InShare", icon: "/appIcons/share.png" },
    { appName: "Instagram", icon: "/appIcons/instagram.png" },
    { appName: "Keka", icon: "/appIcons/keka.png" },
    { appName: "LinkedIn", icon: "/appIcons/linkedin.png" },
    { appName: "Messages", icon: "/appIcons/messages.png" },
    { appName: "Video Player", icon: "/appIcons/videoPlayer.png" },
    { appName: "My Jio", icon: "/appIcons/jio.png" },
    { appName: "OLX India", icon: "/appIcons/olx.png" },
    { appName: "Phone", icon: "/appIcons/phone.png" },
    { appName: "Photos", icon: "/appIcons/photos.png" },
    { appName: "Play Store", icon: "/appIcons/playstore.png" },
    { appName: "Recorder", icon: "/appIcons/recorder.png" },
    { appName: "Settings", icon: "/appIcons/settings.png" },
    { appName: "Teams", icon: "/appIcons/teams.png" },
    { appName: "Telegram", icon: "/appIcons/telegram.png" },
    { appName: "Uber", icon: "/appIcons/uber.png" },
    { appName: "Weather", icon: "/appIcons/weather.png" },
    { appName: "WhatsApp", icon: "/appIcons/whatsapp.png" },
    { appName: "Youtube", icon: "/appIcons/youtube.png" },
    { appName: "YT Music", icon: "/appIcons/ytmusic.png" },
]